In [1]:
import pandas as pd
import re

def get_result(file_path, data_name):
    # 결과를 저장할 리스트
    best_la_auc_values = []

    # 파일을 읽고 각 라인을 처리
    with open(file_path, 'r') as file:
        for line in file:
            # 'Best LA AUC' 값을 찾는다
            match = re.search(r'Best LA AUC: ([0-9.]+)', line)
            if match:
                # 찾은 값을 리스트에 추가한다
                best_la_auc_values.append(float(match.group(1)))

    # 리스트를 사용하여 pandas DataFrame을 생성
    df = pd.DataFrame(best_la_auc_values, columns=[data_name])
    return df

import os

def gather_result(data_name):
    templates_path = ["_1_f_f_result", "_1_t_f_result", "_1_f_t_result", "_1_t_t_result",
                "_5_f_f_result", "_5_t_f_result", "_5_f_t_result", "_5_t_t_result"]
    templates_name = ["_1", "_1_mask", "_1_text", "_1_mask_text",
                      "_5", "_5_mask", "_5_text", "_5_mask_text"]
    df_list = []
    for template_name, template_path in zip(templates_name, templates_path):
        path = data_name + template_path
        name = data_name + template_name

        if not os.path.exists(path):
            continue
        df = get_result(path, name)

        df_list.append(df)

    final_df = pd.concat((df_list), axis=1)
    
    return final_df

def show_result(dir_name):
    data_names = ["breakfast", "banana_juice", "orange_juice", "cherry_juice", "pushpins",
                  "screw_bag", "blue_splicing", "red_splicing", "yellow_splicing"]
    
    result = {}
    
    for data_name in data_names:
        data_path = dir_name + "/" + data_name
        data_df = gather_result(data_path)
        avg_perfo = data_df.mean().tolist()
        result[data_name] = avg_perfo
    
    df = pd.DataFrame(result)
    #df.index = ["1", "1_mask", "1_text", "1_mask_text",
    #                  "5", "5_mask", "5_text", "5_mask_text"]
    
    df.index = ["1_mask","5_mask"]
    return df

def add_avg_perfo(df):
    avg_perfo = df.mean().tolist()
    df.loc[len(df.index)] = avg_perfo
    df.index = df.index.tolist()[:len(df.index)-1] + ["Average"]
    return df

def compare_two_result(df1, df1_name, df2, df2_name):
    #df1 and df2 must share column names and index names
    result = {}
    for col in df1.columns:
        result[col + " " + df1_name] = df1[col]
        result[col + " " + df2_name] = df2[col]
        result["Delta " + col] = df2[col] - df1[col] 
    df = pd.DataFrame(result)
    return df

In [2]:
l = gather_result("num_pos_3/breakfast")
l2 = gather_result("num_pos_3/banana_juice")
l3 = gather_result("num_pos_3/orange_juice")
l4 = gather_result("num_pos_3/cherry_juice")
l5 = gather_result("num_pos_3/pushpins")
l6 = gather_result("num_pos_3/screw_bag")

l7 = gather_result("num_pos_3/blue_splicing")
l8 = gather_result("num_pos_3/red_splicing")
l9 = gather_result("num_pos_3/yellow_splicing")

result = pd.concat([l, l2, l3, l4, l5, l6, l7, l8, l9], axis=1)
result.describe()

,num_pos_3/breakfast_1_mask_text,num_pos_3/banana_juice_1_mask_text,num_pos_3/orange_juice_1_mask_text,num_pos_3/cherry_juice_1_mask_text,num_pos_3/pushpins_1_mask_text,num_pos_3/screw_bag_1_mask_text,num_pos_3/blue_splicing_1_mask_text,num_pos_3/red_splicing_1_mask_text,num_pos_3/yellow_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.765958,0.860707,0.804686,0.853852,0.557792,0.564910,0.690833,0.745640,0.736338
std,0.037102,0.039391,0.040198,0.040479,0.040728,0.047493,0.044317,0.030579,0.031638
min,0.688991,0.795960,0.739169,0.810320,0.480491,0.497487,0.640909,0.700581,0.682292
25%,0.748612,0.836364,0.781167,0.820858,0.539537,0.526550,0.664015,0.722820,0.720753
50%,0.777286,0.877525,0.813439,0.845203,0.553552,0.567219,0.676136,0.741860,0.741186
75%,0.788743,0.881061,0.831123,0.884084,0.572812,0.593395,0.712121,0.771802,0.752404
max,0.812662,0.920202,0.864721,0.925872,0.638398,0.654242,0.775758,0.786628,0.786058

In [3]:
l = gather_result("num_pos_3/breakfast")
l2 = gather_result("num_pos_3/banana_juice")
l3 = gather_result("num_pos_3/orange_juice")
l4 = gather_result("num_pos_3/cherry_juice")
l5 = gather_result("num_pos_3/pushpins")
l6 = gather_result("num_pos_3/screw_bag")

l7 = gather_result("num_pos_3/blue_splicing")
l8 = gather_result("num_pos_3/red_splicing")
l9 = gather_result("num_pos_3/yellow_splicing")

result = pd.concat([l, l2, l3, l4, l5, l6, l7, l8, l9], axis=1)
result.describe()

,num_pos_3/breakfast_1_mask_text,num_pos_3/banana_juice_1_mask_text,num_pos_3/orange_juice_1_mask_text,num_pos_3/cherry_juice_1_mask_text,num_pos_3/pushpins_1_mask_text,num_pos_3/screw_bag_1_mask_text,num_pos_3/blue_splicing_1_mask_text,num_pos_3/red_splicing_1_mask_text,num_pos_3/yellow_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.765958,0.860707,0.804686,0.853852,0.557792,0.564910,0.690833,0.745640,0.736338
std,0.037102,0.039391,0.040198,0.040479,0.040728,0.047493,0.044317,0.030579,0.031638
min,0.688991,0.795960,0.739169,0.810320,0.480491,0.497487,0.640909,0.700581,0.682292
25%,0.748612,0.836364,0.781167,0.820858,0.539537,0.526550,0.664015,0.722820,0.720753
50%,0.777286,0.877525,0.813439,0.845203,0.553552,0.567219,0.676136,0.741860,0.741186
75%,0.788743,0.881061,0.831123,0.884084,0.572812,0.593395,0.712121,0.771802,0.752404
max,0.812662,0.920202,0.864721,0.925872,0.638398,0.654242,0.775758,0.786628,0.786058

In [2]:
get_result("breakfast_box_wrong_case_2.txt", "breakfast_1_f_f").describe()

       breakfast_1_f_f
count        30.000000
mean          0.751461
std           0.047281
min           0.646468
25%           0.710932
50%           0.765533
75%           0.783162
max           0.822703

In [50]:
wrong_1 = get_result("wrong_pos_rule_1.txt", "breakfast_1_f_f")
wrong_3 = get_result("wrong_pos_rule_3.txt", "breakfast_3_f_f")
wrong_5 = get_result("wrong_pos_rule_3_pushpins.txt", "pushpin_3_f_f")
pd.concat([wrong_1, wrong_3, wrong_5], axis=1).describe()

       breakfast_1_f_f  breakfast_3_f_f  pushpin_3_f_f
count         5.000000        30.000000      29.000000
mean          0.715556         0.756227       0.585547
std           0.050646         0.046757       0.036986
min           0.653437         0.655327       0.523810
25%           0.690881         0.715923       0.555622
50%           0.700921         0.764115       0.583612
75%           0.751536         0.792789       0.609094
max           0.781006         0.845027       0.661570

In [3]:
l = gather_result("paper_results/breakfast")
l.describe()

,paper_results/breakfast_1,paper_results/breakfast_1_mask,paper_results/breakfast_1_text,paper_results/breakfast_1_mask_text,paper_results/breakfast_5,paper_results/breakfast_5_mask,paper_results/breakfast_5_text,paper_results/breakfast_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.751669,0.848441,0.759957,0.852104,0.800262,0.890373,0.785174,0.908664
std,0.051702,0.049631,0.038864,0.032388,0.033067,0.029991,0.028711,0.017686
min,0.659343,0.701276,0.662060,0.784196,0.706178,0.822466,0.729034,0.880345
25%,0.711021,0.825478,0.742175,0.827723,0.779707,0.882560,0.765178,0.896498
50%,0.746456,0.853945,0.769431,0.861564,0.805930,0.894755,0.786971,0.906981
75%,0.791873,0.890680,0.786676,0.874852,0.821226,0.909196,0.802977,0.923901
max,0.844437,0.920978,0.816324,0.897472,0.852469,0.935979,0.840421,0.937279

In [4]:
l = gather_result("result/banana_juice")
l.describe()

,result/banana_juice_1,result/banana_juice_1_mask,result/banana_juice_1_text,result/banana_juice_1_mask_text,result/banana_juice_5,result/banana_juice_5_mask,result/banana_juice_5_text,result/banana_juice_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.860168,0.863822,0.855859,0.875774,0.906195,0.906717,0.905438,0.904832
std,0.034312,0.039497,0.040448,0.046308,0.028622,0.030283,0.020284,0.022991
min,0.774747,0.795960,0.775758,0.777778,0.855051,0.828283,0.871212,0.846970
25%,0.843434,0.833838,0.825505,0.841540,0.891793,0.890657,0.893687,0.896212
50%,0.861111,0.863384,0.859343,0.879040,0.908081,0.914646,0.902778,0.908333
75%,0.873864,0.881313,0.883838,0.912500,0.930051,0.929924,0.918813,0.917929
max,0.937374,0.954545,0.931818,0.946465,0.954545,0.954545,0.947475,0.944949

In [5]:
l = gather_result("result/orange_juice")
l.describe()

,result/orange_juice_1,result/orange_juice_1_mask,result/orange_juice_1_text,result/orange_juice_1_mask_text,result/orange_juice_5,result/orange_juice_5_mask,result/orange_juice_5_text,result/orange_juice_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.814029,0.815679,0.819658,0.796640,0.843826,0.860065,0.861774,0.854789
std,0.054182,0.034011,0.038188,0.046503,0.033124,0.028927,0.030765,0.030294
min,0.663130,0.730327,0.732980,0.682582,0.778073,0.792219,0.776304,0.779841
25%,0.791777,0.805482,0.800619,0.772325,0.827365,0.840407,0.846154,0.834881
50%,0.830239,0.821397,0.831123,0.801503,0.849248,0.862511,0.862511,0.856764
75%,0.840849,0.838196,0.845933,0.833333,0.863174,0.878868,0.885500,0.880416
max,0.897436,0.858532,0.882405,0.873563,0.899204,0.908930,0.913351,0.905393

In [6]:
l = gather_result("result/cherry_juice")
l.describe()

,result/cherry_juice_1,result/cherry_juice_1_mask,result/cherry_juice_1_text,result/cherry_juice_1_mask_text,result/cherry_juice_5,result/cherry_juice_5_mask,result/cherry_juice_5_text,result/cherry_juice_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.865431,0.857582,0.866182,0.866764,0.920979,0.919428,0.923595,0.920349
std,0.043257,0.046858,0.027110,0.042810,0.026913,0.027960,0.027750,0.024790
min,0.737645,0.746366,0.805959,0.774709,0.863372,0.856105,0.860465,0.875727
25%,0.843932,0.838481,0.855378,0.845022,0.903525,0.909520,0.906795,0.901344
50%,0.876817,0.864462,0.867006,0.873547,0.925872,0.922238,0.927326,0.919331
75%,0.899346,0.885719,0.885901,0.901890,0.938953,0.934956,0.945494,0.941134
max,0.921512,0.944767,0.920058,0.922238,0.974564,0.973110,0.963663,0.969477

In [11]:
l = gather_result("result/pushpins")
l.describe()

,result/pushpins_1,result/pushpins_1_mask,result/pushpins_5,result/pushpins_5_mask,result/pushpins_5_text,result/pushpins_5_mask_text
count,30.000000,23.000000,30.000000,30.000000,30.000000,30.000000
mean,0.582041,0.569206,0.591868,0.601712,0.615475,0.599539
std,0.042310,0.058216,0.039999,0.041892,0.037950,0.024812
min,0.491161,0.444657,0.520784,0.526278,0.548336,0.537108
25%,0.552058,0.525721,0.564023,0.567069,0.591456,0.587852
50%,0.583771,0.584010,0.586857,0.610846,0.615743,0.600454
75%,0.614767,0.605192,0.613633,0.638816,0.640747,0.618271
max,0.650024,0.671126,0.676541,0.669374,0.711897,0.648989

In [7]:
l = gather_result("result/screw_bag")
l.describe()

,result/screw_bag_1,result/screw_bag_1_mask,result/screw_bag_1_text,result/screw_bag_1_mask_text,result/screw_bag_5,result/screw_bag_5_mask,result/screw_bag_5_text,result/screw_bag_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.565340,0.561092,0.561047,0.570213,0.601456,0.592220,0.589330,0.593658
std,0.040410,0.039391,0.043830,0.040292,0.034838,0.027533,0.029396,0.033558
min,0.483068,0.474812,0.470025,0.484923,0.505026,0.533924,0.522975,0.530932
25%,0.531246,0.529003,0.531052,0.536631,0.585938,0.572836,0.568580,0.565282
50%,0.578347,0.565604,0.563465,0.570929,0.598002,0.594053,0.585677,0.596985
75%,0.592722,0.586649,0.592393,0.600537,0.628365,0.605854,0.610222,0.608749
max,0.631267,0.663396,0.637729,0.647720,0.672251,0.641020,0.642635,0.673148

In [8]:
l = gather_result("result/blue_splicing")
l.describe()

,result/blue_splicing_1,result/blue_splicing_1_mask,result/blue_splicing_1_text,result/blue_splicing_1_mask_text,result/blue_splicing_5,result/blue_splicing_5_mask,result/blue_splicing_5_text,result/blue_splicing_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.740126,0.742828,0.721641,0.734217,0.768561,0.776237,0.782778,0.771111
std,0.052115,0.054462,0.059131,0.046767,0.037607,0.034089,0.031311,0.032191
min,0.653030,0.639394,0.615152,0.656818,0.696970,0.696212,0.722727,0.704545
25%,0.692992,0.700947,0.669129,0.693371,0.748485,0.759091,0.761553,0.755871
50%,0.745076,0.752273,0.728788,0.745833,0.762879,0.782955,0.782576,0.776515
75%,0.784280,0.779924,0.756439,0.773485,0.791477,0.797348,0.799242,0.792424
max,0.835606,0.833333,0.837121,0.804545,0.855303,0.835606,0.848485,0.841667

In [9]:
l = gather_result("result/red_splicing")
l.describe()

,result/red_splicing_1,result/red_splicing_1_mask,result/red_splicing_1_text,result/red_splicing_1_mask_text,result/red_splicing_5,result/red_splicing_5_mask,result/red_splicing_5_text,result/red_splicing_5_mask_text
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,0.765136,0.761570,0.760911,0.780756,0.823081,0.816221,0.812132,0.810504
std,0.032365,0.036990,0.045476,0.029350,0.023624,0.025537,0.021242,0.026445
min,0.659302,0.679651,0.649419,0.727326,0.770349,0.754651,0.767442,0.768023
25%,0.752471,0.743169,0.738227,0.761483,0.808285,0.795785,0.797093,0.789535
50%,0.765698,0.765988,0.761628,0.780233,0.819186,0.821221,0.813372,0.807558
75%,0.785901,0.790552,0.781977,0.803343,0.839390,0.835029,0.829942,0.830087
max,0.811628,0.820349,0.856977,0.840698,0.871512,0.862791,0.849419,0.863372

In [13]:
l = gather_result("result/yellow_splicing")
l.describe()

,result/yellow_splicing_1,result/yellow_splicing_1_mask,result/yellow_splicing_1_text,result/yellow_splicing_1_mask_text
count,30.000000,30.000000,30.000000,30.000000
mean,0.758226,0.761512,0.762767,0.746421
std,0.031938,0.032325,0.034298,0.039475
min,0.696314,0.702724,0.677885,0.647436
25%,0.740184,0.742388,0.746995,0.725561
50%,0.753606,0.760016,0.762019,0.750801
75%,0.777043,0.780649,0.783454,0.765024
max,0.822917,0.836538,0.828526,0.834135

In [14]:
df1 = show_result("paper_results")
df2 = show_result("neg_loss_50")
df = compare_two_result(df1, "base", df2, "neg_50")

ValueError: Length mismatch: Expected axis has 4 elements, new values have 8 elements

In [9]:
df1 = add_avg_perfo(show_result("glclip").T)
df1

                   1_mask    5_mask
breakfast        0.702351  0.715037
banana_juice     0.842020  0.908485
orange_juice     0.682228  0.774978
cherry_juice     0.849273  0.887573
pushpins         0.554846  0.595151
screw_bag        0.549025  0.604442
blue_splicing    0.760833  0.795909
red_splicing     0.713721  0.763895
yellow_splicing  0.693750  0.709054
Average          0.705339  0.750503

In [4]:
df1 = add_avg_perfo(show_result("RIS").T)
df1

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
breakfast,0.741789,0.831339,0.732119,0.829246,0.800213,0.858103,0.801140,0.866696
banana_juice,0.845816,0.815067,0.848199,0.830101,0.904798,0.857845,0.905556,0.873030
orange_juice,0.782169,0.780077,0.790333,0.779664,0.838255,0.825346,0.826702,0.835455
cherry_juice,0.857292,0.835925,0.857025,0.837209,0.920506,0.876453,0.918096,0.883212
pushpins,0.592022,0.573099,0.587689,0.573486,0.623453,0.630510,0.621033,0.587414
screw_bag,0.569865,0.606680,0.580297,0.592956,0.604607,0.642125,0.609584,0.649134
blue_splicing,0.689646,0.734268,0.695859,0.730328,0.737929,0.774937,0.738990,0.800202
red_splicing,0.715368,0.775310,0.726240,0.781395,0.774147,0.838178,0.765562,0.842791
yellow_splicing,0.689463,0.730369,0.699386,0.723024,0.720967,0.765037,0.726629,0.752457
Average,0.720381,0.742459,0.724127,0.741934,0.769431,0.785393,0.768143,0.787821

In [34]:
df1 = add_avg_perfo(show_result("num_neg_1").T)
df1

                        1    1_mask    1_text  1_mask_text
breakfast        0.730085  0.838985  0.756166     0.858068
banana_juice     0.858283  0.838889  0.818939     0.855758
orange_juice     0.788108  0.819805  0.796198     0.782095
cherry_juice     0.855959  0.823765  0.846003     0.856686
pushpins         0.582672  0.568920  0.590639     0.617125
screw_bag        0.581755  0.610668  0.583726     0.598534
blue_splicing    0.687273  0.745985  0.710682     0.726515
red_splicing     0.712384  0.734012  0.672791     0.761337
yellow_splicing  0.680208  0.759455  0.665304     0.758413
Average          0.719636  0.748943  0.715605     0.757170

In [37]:
df1 = add_avg_perfo(show_result("num_neg_3").T)
df1

                        1    1_mask    1_text  1_mask_text
breakfast        0.754311  0.844224  0.731113     0.865533
banana_juice     0.869747  0.871162  0.834747     0.873990
cherry_juice     0.837718  0.874491  0.889099     0.874637
pushpins         0.617754  0.602982  0.583751     0.599908
screw_bag        0.556602  0.585880  0.579897     0.594412
blue_splicing    0.677500  0.726439  0.702273     0.721667
red_splicing     0.683081  0.761395  0.679942     0.774186
yellow_splicing  0.673878  0.757612  0.697115     0.755048
Average          0.708824  0.753023  0.712242     0.757423

In [27]:
df1 = add_avg_perfo(show_result("min_score").T)
transposed = df1.T
transposed["juice_bottle"] = transposed["banana_juice"] + transposed["orange_juice"] + transposed["cherry_juice"]
transposed["juice_bottle"] = transposed["juice_bottle"]/3

transposed["splicing"] = transposed["blue_splicing"] + transposed["red_splicing"] + transposed["yellow_splicing"]
transposed["splicing"] = transposed["splicing"]/3

transposed.drop(["banana_juice", "orange_juice", "cherry_juice", "blue_splicing", "red_splicing", "yellow_splicing", "Average"], axis=1, inplace=True)

transposed = transposed.T
transposed.loc["Average"] = transposed.mean().to_list()
transposed.T

             breakfast  pushpins  screw_bag  juice_bottle  splicing   Average
1             0.744320  0.609365   0.598682      0.831740  0.708883  0.698598
1_mask        0.786863  0.589548   0.577999      0.840124  0.770780  0.713063
1_text        0.759956  0.604021   0.578537      0.814597  0.714450  0.694312
1_mask_text   0.789310  0.609540   0.580734      0.836581  0.775810  0.718395
5             0.780445  0.610100   0.630545      0.880555  0.740416  0.728412
5_mask        0.795539  0.617077   0.601372      0.879042  0.800850  0.738776
5_text        0.769826  0.629019   0.625130      0.878381  0.748277  0.730127
5_mask_text   0.801413  0.598877   0.608084      0.880513  0.808214  0.739420

In [5]:
df1 = add_avg_perfo(show_result("num_neg_rule").T)
df1.T

,breakfast,banana_juice,orange_juice,cherry_juice,pushpins,screw_bag,blue_splicing,red_splicing,yellow_splicing,Average
1,0.757447,0.874040,0.775906,0.866388,0.585348,0.580430,0.708636,0.693953,0.708413,0.727840
1_mask,0.873943,0.863081,0.826083,0.850036,0.578046,0.602016,0.753295,0.793081,0.760417,0.766667
1_text,0.734550,0.879293,0.782405,0.850073,0.591468,0.607736,0.687879,0.715349,0.701843,0.727844
1_mask_text,0.860572,0.875404,0.812378,0.851890,0.615134,0.603596,0.748485,0.787733,0.781971,0.770796
5,0.790598,0.905354,0.813086,0.912246,0.617738,0.613704,0.726477,0.753605,0.736378,0.763243
5_mask,0.897484,0.904949,0.872591,0.914535,0.576258,0.610656,0.799091,0.840814,0.804046,0.802269
5_text,0.802292,0.922753,0.827542,0.898401,0.607489,0.606934,0.720833,0.776890,0.724279,0.765268
5_mask_text,0.897815,0.911111,0.845093,0.917515,0.616077,0.609893,0.781212,0.822733,0.810817,0.801363

In [24]:
transposed = df1.T
transposed["juice_bottle"] = transposed["banana_juice"] + transposed["orange_juice"] + transposed["cherry_juice"]
transposed["juice_bottle"] = transposed["juice_bottle"]/3

transposed["splicing"] = transposed["blue_splicing"] + transposed["red_splicing"] + transposed["yellow_splicing"]
transposed["splicing"] = transposed["splicing"]/3

transposed.drop(["banana_juice", "orange_juice", "cherry_juice", "blue_splicing", "red_splicing", "yellow_splicing", "Average"], axis=1, inplace=True)

transposed = transposed.T
transposed.loc["Average"] = transposed.mean().to_list()
transposed.T

             breakfast  pushpins  screw_bag  juice_bottle  splicing   Average
1             0.757447  0.585348   0.580430      0.838778  0.703668  0.693134
1_mask        0.873943  0.578046   0.602016      0.846400  0.768931  0.733867
1_text        0.734550  0.591468   0.607736      0.837257  0.701690  0.694540
1_mask_text   0.860572  0.615134   0.603596      0.846557  0.772730  0.739718
5             0.790598  0.617738   0.613704      0.876895  0.738820  0.727551
5_mask        0.897484  0.576258   0.610656      0.897358  0.814650  0.759281
5_text        0.802292  0.607489   0.606934      0.882899  0.740667  0.728056
5_mask_text   0.897815  0.616077   0.609893      0.891239  0.804921  0.763989

In [9]:
df1 = add_avg_perfo(show_result("paper_results").T)
df1

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
breakfast,0.751669,0.848441,0.759957,0.852104,0.800262,0.890373,0.785174,0.908664
banana_juice,0.830556,0.881212,0.844007,0.880909,0.904285,0.903636,0.900269,0.905101
orange_juice,0.787091,0.791998,0.791247,0.808017,0.831123,0.852933,0.831241,0.855821
cherry_juice,0.850606,0.860005,0.850630,0.869283,0.925363,0.922190,0.912016,0.919525
pushpins,0.587879,0.578802,0.593754,0.578041,0.618591,0.605345,0.610984,0.612271
screw_bag,0.558065,0.569541,0.562729,0.567107,0.613809,0.593746,0.603854,0.598222
blue_splicing,0.706124,0.754495,0.706768,0.743586,0.740455,0.787727,0.739040,0.783081
red_splicing,0.708508,0.776444,0.724496,0.770620,0.766948,0.819360,0.766318,0.819574
yellow_splicing,0.689396,0.754915,0.680542,0.767201,0.727724,0.794418,0.731571,0.798691
Average,0.718877,0.757317,0.723792,0.759652,0.769840,0.796636,0.764496,0.800106

In [52]:
#last try
l = gather_result("screw_push/screw_bag")
l.describe()

,screw_push/screw_bag_1,screw_push/screw_bag_1_mask,screw_push/screw_bag_1_text,screw_push/screw_bag_1_mask_text,screw_push/screw_bag_5,screw_push/screw_bag_5_mask,screw_push/screw_bag_5_text,screw_push/screw_bag_5_mask_text
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.571796,0.586984,0.580433,0.615361,0.609633,0.609480,0.617844,0.608933
std,0.033976,0.032514,0.036489,0.033739,0.023061,0.032389,0.034810,0.028237
min,0.502872,0.543616,0.515197,0.547206,0.562792,0.557886,0.573412,0.575506
25%,0.553690,0.561214,0.557041,0.606423,0.595264,0.580060,0.594801,0.585729
50%,0.579948,0.590583,0.581698,0.621709,0.614904,0.616235,0.607365,0.605660
75%,0.594831,0.602280,0.608794,0.633548,0.621537,0.637078,0.640541,0.622480
max,0.612570,0.646823,0.630609,0.664922,0.643981,0.646165,0.677007,0.660734

In [14]:
#last try
l = gather_result("screw_push/pushpins")
l.describe()

,screw_push/pushpins_1,screw_push/pushpins_1_mask,screw_push/pushpins_1_text,screw_push/pushpins_1_mask_text,screw_push/pushpins_5,screw_push/pushpins_5_mask,screw_push/pushpins_5_text,screw_push/pushpins_5_mask_text
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.595772,0.576644,0.586264,0.589469,0.631108,0.588207,0.620433,0.596878
std,0.034507,0.035769,0.034006,0.031554,0.048142,0.044527,0.035237,0.033569
min,0.538541,0.515249,0.535834,0.532649,0.563466,0.505574,0.575968,0.554228
25%,0.570821,0.567985,0.564103,0.585394,0.604893,0.558887,0.602723,0.569995
50%,0.601609,0.584329,0.584408,0.597627,0.619804,0.592431,0.611801,0.595636
75%,0.620431,0.591038,0.603420,0.612856,0.646331,0.629101,0.648600,0.621675
max,0.643335,0.635889,0.648670,0.616499,0.715799,0.639234,0.677576,0.650661

In [40]:
#last try
l = gather_result("text/yellow_splicing")
l.describe()

,text/yellow_splicing_1,text/yellow_splicing_1_mask,text/yellow_splicing_1_text,text/yellow_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.703966,0.756330,0.705288,0.756010
std,0.047502,0.035517,0.037005,0.021555
min,0.627404,0.704327,0.641827,0.739583
25%,0.673978,0.729167,0.690104,0.743389
50%,0.710737,0.756010,0.701522,0.748798
75%,0.739784,0.775240,0.731370,0.752404
max,0.761218,0.822115,0.756410,0.806090

In [41]:
#last try
l = gather_result("text/banana_juice")
l.describe()

,text/banana_juice_1,text/banana_juice_1_mask,text/banana_juice_1_text,text/banana_juice_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.833737,0.877020,0.840253,0.858990
std,0.069049,0.052135,0.059725,0.051294
min,0.714646,0.801010,0.705556,0.768182
25%,0.817677,0.839015,0.817929,0.822854
50%,0.829419,0.881313,0.850000,0.864394
75%,0.878093,0.915909,0.878283,0.895455
max,0.940909,0.946970,0.919697,0.926263

In [30]:
df3 = add_avg_perfo(show_result("last_chance").T)
df3.T

,breakfast,banana_juice,orange_juice,cherry_juice,pushpins,screw_bag,blue_splicing,red_splicing,yellow_splicing,Average
1,0.750236,0.838258,0.776172,0.842733,0.609854,0.595486,0.707879,0.697384,0.677204,0.721689
1_mask,0.828916,0.813838,0.795579,0.866206,0.609942,0.616202,0.758864,0.786105,0.768429,0.760453
1_text,0.751288,0.852020,0.788948,0.851235,0.603962,0.591310,0.700606,0.695959,0.694151,0.725498
1_mask_text,0.855422,0.824242,0.746242,0.866352,0.610663,0.655250,0.734621,0.786919,0.758654,0.759818
5,0.819525,0.886414,0.839346,0.912173,0.624351,0.607557,0.734129,0.782035,0.711298,0.768536
5_mask,0.860129,0.863384,0.828028,0.929033,0.593251,0.664530,0.811667,0.822326,0.798878,0.796803
5_text,0.802977,0.901667,0.837577,0.914317,0.603114,0.620929,0.747348,0.775523,0.723237,0.769632
5_mask_text,0.859568,0.871717,0.823431,0.916788,0.610225,0.687151,0.771894,0.819477,0.806330,0.796287

In [3]:
df3 = add_avg_perfo(show_result("num_neg_rule").T)
df3

ValueError: Length mismatch: Expected axis has 5 elements, new values have 8 elements

In [51]:
df3 = add_avg_perfo(show_result("neg_loss_150").T)
df3

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
breakfast,0.748888,0.854111,0.747017,0.858827,0.795773,0.889791,0.800423,0.905617
banana_juice,0.820177,0.868367,0.841111,0.871279,0.900345,0.905219,0.903813,0.911481
orange_juice,0.792190,0.818774,0.777660,0.810669,0.826879,0.853139,0.831329,0.852667
cherry_juice,0.866255,0.867127,0.852955,0.852374,0.917066,0.914559,0.918047,0.922408
pushpins,0.598052,0.581831,0.594353,0.579757,0.633202,0.597508,0.622687,0.621779
screw_bag,0.589763,0.571836,0.593013,0.575505,0.629968,0.609801,0.616782,0.609889
blue_splicing,0.702348,0.750467,0.704672,0.747424,0.731061,0.788106,0.740025,0.796187
red_splicing,0.705785,0.787539,0.714138,0.779767,0.771667,0.827955,0.778411,0.835484
yellow_splicing,0.694952,0.775855,0.693536,0.765839,0.725748,0.796608,0.722596,0.801095
Average,0.724268,0.763990,0.724273,0.760160,0.770190,0.798076,0.770457,0.806290

In [34]:
df1 = add_avg_perfo(show_result("add").T)
df1

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
breakfast,0.758050,0.847360,0.758481,0.860631,0.789464,0.909190,0.798346,0.906089
banana_juice,0.850657,0.864596,0.876566,0.870909,0.918636,0.903712,0.898030,0.907778
orange_juice,0.775243,0.819010,0.804023,0.801768,0.830239,0.886340,0.840937,0.865694
cherry_juice,0.857195,0.876490,0.842078,0.855087,0.910102,0.916933,0.905451,0.905596
pushpins,0.587064,0.592578,0.581669,0.590564,0.611670,0.597213,0.601863,0.599749
screw_bag,0.592629,0.605268,0.620106,0.594193,0.613417,0.602830,0.632120,0.614033
blue_splicing,0.687803,0.731364,0.713333,0.733636,0.748788,0.789432,0.757992,0.784621
red_splicing,0.716453,0.800640,0.710058,0.782674,0.761134,0.823605,0.775698,0.836047
yellow_splicing,0.683373,0.776522,0.690465,0.784696,0.723157,0.799519,0.729046,0.803686
Average,0.723163,0.768203,0.732975,0.763795,0.767401,0.803197,0.771054,0.802588

In [35]:
df3 = add_avg_perfo(show_result("paper_results").T)
df3

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
breakfast,0.751669,0.848441,0.759957,0.852104,0.800262,0.890373,0.785174,0.908664
banana_juice,0.830556,0.881212,0.844007,0.880909,0.904285,0.903636,0.900269,0.905101
orange_juice,0.787091,0.791998,0.791247,0.808017,0.831123,0.852933,0.831241,0.855821
cherry_juice,0.850606,0.860005,0.850630,0.869283,0.925363,0.922190,0.912016,0.919525
pushpins,0.587879,0.578802,0.593754,0.578041,0.618591,0.605345,0.610984,0.612271
screw_bag,0.558065,0.569541,0.562729,0.567107,0.613809,0.593746,0.603854,0.598222
blue_splicing,0.706124,0.754495,0.706768,0.743586,0.740455,0.787727,0.739040,0.783081
red_splicing,0.708508,0.776444,0.724496,0.770620,0.766948,0.819360,0.766318,0.819574
yellow_splicing,0.689396,0.754915,0.680542,0.767201,0.727724,0.794418,0.731571,0.798691
Average,0.718877,0.757317,0.723792,0.759652,0.769840,0.796636,0.764496,0.800106

In [36]:
df3.T

,breakfast,banana_juice,orange_juice,cherry_juice,pushpins,screw_bag,blue_splicing,red_splicing,yellow_splicing,Average
1,0.751669,0.830556,0.787091,0.850606,0.587879,0.558065,0.706124,0.708508,0.689396,0.718877
1_mask,0.848441,0.881212,0.791998,0.860005,0.578802,0.569541,0.754495,0.776444,0.754915,0.757317
1_text,0.759957,0.844007,0.791247,0.850630,0.593754,0.562729,0.706768,0.724496,0.680542,0.723792
1_mask_text,0.852104,0.880909,0.808017,0.869283,0.578041,0.567107,0.743586,0.770620,0.767201,0.759652
5,0.800262,0.904285,0.831123,0.925363,0.618591,0.613809,0.740455,0.766948,0.727724,0.769840
5_mask,0.890373,0.903636,0.852933,0.922190,0.605345,0.593746,0.787727,0.819360,0.794418,0.796636
5_text,0.785174,0.900269,0.831241,0.912016,0.610984,0.603854,0.739040,0.766318,0.731571,0.764496
5_mask_text,0.908664,0.905101,0.855821,0.919525,0.612271,0.598222,0.783081,0.819574,0.798691,0.800106

In [38]:
import numpy as np

neg = np.array(df1.loc["Average"].tolist())
base = np.array(df3.loc["Average"].tolist())
delta = (neg-base)/base*100

In [39]:
loss_compare = {}
loss_compare["Positive_loss_only(ROC-AUC)"] = base
loss_compare["Positive+Negative loss(ROC-AUC)"] = neg
loss_compare["Delta(%)"]= delta
df = pd.DataFrame(loss_compare)
df.index = ["1", "1_mask", "1_text", "1_mask_text",
                      "5", "5_mask", "5_text", "5_mask_text"]
df.T

,1,1_mask,1_text,1_mask_text,5,5_mask,5_text,5_mask_text
Positive_loss_only(ROC-AUC),0.718877,0.757317,0.723792,0.759652,0.769840,0.796636,0.764496,0.800106
Positive+Negative loss(ROC-AUC),0.723163,0.768203,0.732975,0.763795,0.767401,0.803197,0.771054,0.802588
Delta(%),0.596203,1.437465,1.268771,0.545441,-0.316849,0.823536,0.857761,0.310277

In [42]:
#last try
l = gather_result("text/pushpins")
l.describe()

,text/pushpins_1,text/pushpins_1_mask,text/pushpins_1_text,text/pushpins_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.601501,0.578141,0.596054,0.576059
std,0.033784,0.057194,0.026141,0.039929
min,0.564023,0.468427,0.566014,0.497054
25%,0.571060,0.552118,0.576525,0.558379
50%,0.592292,0.565456,0.588708,0.586081
75%,0.632346,0.619874,0.609791,0.595557
max,0.649387,0.673993,0.641583,0.631311

In [43]:
l = gather_result("text/screw_bag")
l.describe()

,text/screw_bag_1,text/screw_bag_1_mask,text/screw_bag_1_text,text/screw_bag_1_mask_text
count,10.000000,10.000000,10.000000,6.000000
mean,0.587513,0.569774,0.557323,0.570899
std,0.056367,0.045565,0.046537,0.032872
min,0.464940,0.498863,0.499641,0.517141
25%,0.560137,0.541702,0.524687,0.553271
50%,0.605780,0.562119,0.554296,0.584420
75%,0.627558,0.608270,0.573808,0.593649
max,0.643772,0.642336,0.661721,0.599797

In [54]:
l = gather_result("num_neg_rule/screw_bag")
l.describe()

       num_neg_rule/screw_bag_1
count                 10.000000
mean                   0.605427
std                    0.055282
min                    0.507838
25%                    0.564175
50%                    0.618134
75%                    0.649665
max                    0.675452

In [44]:
l = gather_result("text/banana_juice")
l.describe()

,text/banana_juice_1,text/banana_juice_1_mask,text/banana_juice_1_text,text/banana_juice_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.833737,0.877020,0.840253,0.858990
std,0.069049,0.052135,0.059725,0.051294
min,0.714646,0.801010,0.705556,0.768182
25%,0.817677,0.839015,0.817929,0.822854
50%,0.829419,0.881313,0.850000,0.864394
75%,0.878093,0.915909,0.878283,0.895455
max,0.940909,0.946970,0.919697,0.926263

In [45]:
l = gather_result("text/orange_juice")
l.describe()

,text/orange_juice_1,text/orange_juice_1_mask,text/orange_juice_1_text,text/orange_juice_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.786030,0.795402,0.789744,0.826348
std,0.034775,0.037225,0.045339,0.030878
min,0.736516,0.750663,0.667551,0.778073
25%,0.756852,0.764147,0.786030,0.804156
50%,0.792661,0.790451,0.800177,0.830681
75%,0.808576,0.825597,0.814324,0.839744
max,0.834660,0.854111,0.826702,0.880637

In [46]:
l = gather_result("text/cherry_juice")
l.describe()

,text/cherry_juice_1,text/cherry_juice_1_mask,text/cherry_juice_1_text,text/cherry_juice_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.855015,0.870203,0.868459,0.874855
std,0.036156,0.032050,0.040213,0.030598
min,0.808866,0.808866,0.792151,0.839390
25%,0.829397,0.851381,0.846475,0.844840
50%,0.846657,0.872456,0.867006,0.873547
75%,0.883903,0.895167,0.899709,0.900254
max,0.915698,0.911337,0.930233,0.922238

In [47]:
l = gather_result("text/yellow_splicing")
l.describe()

,text/yellow_splicing_1,text/yellow_splicing_1_mask,text/yellow_splicing_1_text,text/yellow_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.703966,0.756330,0.705288,0.756010
std,0.047502,0.035517,0.037005,0.021555
min,0.627404,0.704327,0.641827,0.739583
25%,0.673978,0.729167,0.690104,0.743389
50%,0.710737,0.756010,0.701522,0.748798
75%,0.739784,0.775240,0.731370,0.752404
max,0.761218,0.822115,0.756410,0.806090

In [48]:
l = gather_result("text/red_splicing")
l.describe()

,text/red_splicing_1,text/red_splicing_1_mask,text/red_splicing_1_text,text/red_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.729419,0.775291,0.698314,0.781047
std,0.060504,0.024274,0.036134,0.019942
min,0.656395,0.745930,0.659884,0.735465
25%,0.682413,0.759448,0.665988,0.782122
50%,0.708430,0.767151,0.692151,0.786337
75%,0.771948,0.794186,0.725436,0.789244
max,0.825581,0.821512,0.753488,0.805814

In [49]:
l = gather_result("text/blue_splicing")
l.describe()

,text/blue_splicing_1,text/blue_splicing_1_mask,text/blue_splicing_1_text,text/blue_splicing_1_mask_text
count,10.000000,10.000000,10.000000,10.000000
mean,0.713636,0.771288,0.691439,0.721364
std,0.038797,0.041062,0.027362,0.050263
min,0.662121,0.683333,0.643939,0.639394
25%,0.684091,0.756629,0.675758,0.680492
50%,0.706061,0.783333,0.691288,0.724621
75%,0.740530,0.804167,0.715530,0.766288
max,0.779545,0.809848,0.728030,0.778788